<?php

/**
 * @file
 * Export module.
 *
 * @author Fang Jin <fang@designhammer.com>
 */

/**
 * Implements hook_menu().
 */
function pgh_awards_export_menu() {
  $items = array();

  // Calculate category score for one application.
  $items['admin/export'] = array(
    'title' => 'Export applications',
    'description' => 'Export application forms value and questions',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pgh_awards_export_form'),
    'access arguments' => array('access administration pages'),
  );

  return $items;
}

/**
 * Export form.
 */
function pgh_awards_export_form($form, &$form_state, $apptype_tag = NULL) {
  $form['description'] = array(
    '#markup' => 'This will take a few minutes to export all applications of this application type, proceed ? <br />',
  );
  $atids = pgh_api_find_nodes(
    array(
      'type' => 'apptype',
    ),
    NULL, TRUE
  );
  $apptypes = node_load_multiple($atids);
  $options = array();
  foreach ($apptypes as &$apptype) {
    $options[$apptype->title] = $apptype->body['und'][0]['value'];
  }
  $form['apptype'] = array(
    '#type' => 'select',
    '#title' => 'Choose application type',
    '#options' => $options,
    '#default_value' => $apptype_tag,
  );

  $form['all'] = array(
    '#type' => 'checkbox',
    '#title' => 'Process all',
    '#description' => 'Check this if you are sure you want to export all the applications',
    '#default_value' => 0,
  );
  $form['debug'] = array(
    '#type' => 'textfield',
    '#title' => '[Debug] Set how many applications to process',
    '#default_value' => 1,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Export',
  );

  return $form;
}
