<?php

/**
 * @file
 * Dashboard module.
 *
 * @author Jay Roberts <jay@designhammer.com>
 */

/**
 * Implements hook_menu().
 */
function pgh_dashboard_menu() {
  $items = array();

  $items['dashboard'] = array(
    'title' => 'Dashboard',
    'description' => 'Fill an application',
    'page callback' => 'pgh_dashboard_page',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Page callback for the dashboard.
 *
 * Currently no additional processing occurs here. 
 * We define the menu link so that the Drupal menu system returns
 * 200 instead of 404 for our page__dashboard.tpl.php template.
 *
 * @return string
 *   An empty string.
 */
function pgh_dashboard_page() {
  return '';
}

/**
 * Make view tab disappear when editing workgroup.
 *
 * @author Fang Jin <fang@designhammer.com>
 */
function pgh_dashboard_menu_alter(&$items) {
  $items['node/%node/view']['access callback'] = 'pgh_dashboard_disable_node_view_tab';
  $items['node/%node/view']['access arguments'] = array(1);
}

/**
 * Access control function to just alter node view tab.
 *
 * @author Fang Jin <fang@designhammer.com>
 */
function pgh_dashboard_disable_node_view_tab($node) {
  if ($node->type == 'business_unit') {
    return FALSE;
  }
  return TRUE;
}
