<?php

/**
 * @file
 * Dashboard module.
 *
 * @author Jay Roberts <jay@designhammer.com>
 */

/**
 * Implementation of hook_menu().
 */
function pgh_dashboard_menu() {
  $items = array();

  $items['dashboard'] = array(
    'title' => 'Dashboard',
    'description' => 'Fill an application',
    'page callback' => 'pgh_dashboard_page',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Page callback for the dashboard.
 *
 * Currently no additional processing occurs here. We define the menu link so that the Drupal menu system returns
 * 200 instead of 404 for our page__dashboard.tpl.php template.
 *
 * @return string
 *   An empty string.
 */
function pgh_dashboard_page() {
  return '';
}
