<?php

/**
 * Implementation of hook_menu().
 */
function pgh_application_menu() {
  $items = array();

  $items['applications'] = array(
    'title' => 'All applications',
    'description' => 'List all applications',
    'page callback' => 'pgh_application_list_page',
    'page arguments' => array(),
    'access callback' => TRUE,
  );

  // Menu links for testing the Form API.
  $items['testform'] = array(
    'title' => 'Form example',
    'description' => 'Test form features',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pgh_application_testform'),
    'access callback' => TRUE,
  );
  $items['testfile'] = array(
    'title' => 'File example',
    'description' => 'Test file upload',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pgh_application_fileform'),
    'access callback' => TRUE,
  );
  $items['testmedia'] = array(
    'title' => 'Media example',
    'description' => 'Test media file upload',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pgh_application_mediaform'),
    'access callback' => TRUE,
  );

  return $items;

}

/**
 * Implementation of hook_block_info().
 */
function pgh_application_block_info() {
  $blocks = array();

  $blocks['application_category_menu'] = array(
    'info' => t('Application Category Menu'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function pgh_application_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'application_category_menu':
      $block['subject'] = t('Application Category Menu');
      $application_nid = pgh_application_current_application_nid();
      $category_links = pgh_application_category_links($application_nid);

      if ($category_links) {
        $block['content'] = array(
          'list' => array(
            '#theme' => 'item_list',
            '#type' => 'ul',
            '#attributes' => array('class' => 'category-menu'),
            '#items' => $category_links,
          ),
        );
      }
      else {
        $block['content'] = 'No category items';
      }
      break;
  }
  return $block;
}

/**
 * Implementation of hook_theme().
 */
function pgh_application_theme() {
  return array(
    'form_table' => array(
      'render element' => 'element'
    )
  );
}

function theme_form_table($vars) {
  $element = $vars['element'];

  $header = array('c1', 'c2');
  foreach (element_children($element) as $key) {
    $rows[] = array(
      array('data' => 'r1'),
      array('data' => render($element[$key]))
    );
  }

  return theme('table', array('header' => $header, 'rows' => $rows));
}

/**
 * form test
 */
function pgh_application_testform($form, &$form_state) {
  $form['abc'][3] = array(
    '#type' => 'textfield',
    '#title' => 'abc',
  );

  $form['abc']['def'] = array(
    '#prefix' => '',
    '#tree' => TRUE,
    '#theme' => 'form_table'
  );

  $form['abc']['def'][4] = array(
    '#type' => 'textfield',
    '#title' => 'def',
    '#tree' => FALSE,
    // '#attributes' => array('id'=> 'edit-4', 'name' => '4'),
  );

  $form['option'] = array(
    '#type' => 'radios',
    '#title' => 'select the following',
    '#options' => array(0 => t('Closed'), 1 => t('Active')),
    '#default_value' => 0
  );

  $form['display'] = array(
    '#type' => 'textfield',
    '#title' => 'display me',
    '#states' => array(
      'visible' => array(
        ':input[name="option"]' => array('value' => 1)
      ),
    ),
  );

  // $form['abc']['def'] = array(
  //   '#markup' => render($form['abc']['def']),
  // );


  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'submit',
  );
  return $form;
}

function pgh_application_testform_submit($form, &$form_state) {
  dsm($form_state['values']);
}

function pgh_application_fileform($form, &$form_state) {
  $form['pgh'] = array(
    '#type' => 'file',
    '#title' => t('Upload video'),
    '#size' => 48,
    '#description' => t('Pick a video file to upload.'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'submit',
  );
  return $form;
}

function pgh_application_fileform_submit($form, &$form_state) {
  dsm($_FILES);
  $file = file_save_upload('pgh', array('file_validate_extensions' => array()), 'private://pgh');
  $file->status = 1;
  dsm($file);
  file_save($file);
}

function pgh_application_mediaform($form, &$form_state) {
  $form['pgh'] = array(
    '#type' => 'media',
    '#title' => t('Upload video'),
    '#input' => TRUE,
    '#media_options' => array(
      'global' => array(
        'types' => array('document'),
        'schemes' => array('http'),
      ),
    ),
    '#description' => t('Pick a video file to upload.'),
    '#attached' => array(),
    '#extended' => TRUE,
    // '#value' => array('fid' => 22),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'submit',
  );
  return $form;
}

/**
 * Returns the nid of the currently displayed application or FALSE if th current page is not a valid application.
 *
 * @return int
 *   The nid of the currently displayed application or boolean FALSE.
 */
function pgh_application_current_application_nid() {
  if (arg(0) == 'application' && is_numeric(arg(1))) {
    $application_node = node_load(arg(1));
    if ($application_node->type == 'application') {
      return $application_node->nid;
    }
    else {
      // Supplied nid is invalid.
      return FALSE;
    }
  }
  else {
    // This is not an application page.
    return FALSE;
  }
}

/**
 * Returns an array of links to category pages for the specified application. Can be passed to theme_item_list().
 *
 * @param int $application_nid
 *   The nid of the application to generate category links for.
 *
 * @return array
 *   An array of links or an empty array if none are found or #application_nid is invalid.
 *
 * @author Jay Roberts <jay@designhammer.com>
 */
function pgh_application_category_links($application_nid) {
  $application_node = node_load($application_nid);
  if (!$application_node) {
    return array();
  }

  $application_wrapper = entity_metadata_wrapper('node', $application_node);
  $app_type_node = $application_wrapper->field_application_type->value();
  $app_type_wrapper = entity_metadata_wrapper('node', $app_type_node);

  $items = array();
  foreach ($app_type_wrapper->field_apptype_categories->getIterator() as $category_wrapper) {
    $label = $category_wrapper->getIdentifier() . ' (' . $category_wrapper->title->value() . ') ' . $category_wrapper->body->value->raw();
    $options = array(
      'attributes' => array(
        'class' => array(
          'category-link',
          str_replace('_', '-', $category_wrapper->title->value()),
        ),
      )
    );
    $items[] = l($label, 'application/' . $application_nid . '/category/' . $category_wrapper->getIdentifier() . '/edit', $options);
  }

  return $items;
}

function pgh_application_mediaform_submit($form, &$form_state) {
  dsm($form);
  dsm($form_state);
  dsm($_FILES);
}

/**
 * Return a page listing all applications
 */
function pgh_application_list_page() {

  $query = new EntityFieldQuery();
  $result = $query->entityCondition('entity_type', 'node')
                  ->propertyCondition('type', 'application')
                  ->execute();
  if (empty($result['node'])) return '';

  $lists = array();
  foreach ($result['node'] as $nid => &$value) {

    $app = node_load($nid);
    $app_wrapper = entity_metadata_wrapper('node', $app);


    $type = $app_wrapper->field_application_type->value();
    $type_wrapper = entity_metadata_wrapper('node', $type);

    $type_caption = $type_wrapper->body->value->raw();

    $lists[] = l($nid . ' - ' . $type_caption, 'application/' . $nid . '/category//edit');
  }

  $out = array(
    '#theme' => 'item_list',
    '#items' => $lists,
    '#title' => t(''),
    // '#attributes' => array('class' => array('my-links')),
  );

  return drupal_render($out);
}


